Adding scanner plant rounter
fga-eps-mds/2020.1-Grupo2-BackEnd pull request #117
Opened 2020-10-20 22:34 UTC by RuanMoura

This pull request resolve the issue #83 .

- [ ] O sistema deve retornar ao usuário informações sobre a planta scanneada
- [ ] O sistema deve identificar a planta scanneada
- [ ] O usuário poderá scannear a planta por meio da câmera do celular
- [ ] O usuário poderá acessar a câmera do celular

2020-10-30 00:14 UTC, rafaelmakaha reviewed
Aprovado

2020-10-30 00:21 UTC, rafaelmakaha requested changes
Resolver conflitos, por favor

2020-11-16 15:24 UTC, joaovitorml requested changes
Falta apenas resolver conflitos e corrigir lint

2020-11-26 22:02 UTC, joaovitorml approved these changes
gostei e aprovei

2020-11-26 22:03 UTC, merged