Refatora dependências do projeto e configuração de Eslint
fga-eps-mds/2020.1-Grupo2-BackEnd pull request #122
Opened 2020-11-03 19:22 UTC by rafaelmakaha

# Descrição

Este pull request fecha #121.

- [ ] Remover dependências não utilizadas
- [ ] `npx eslint --init` para renovar configuração de es-lint

2020-11-03 19:31 UTC, rafaelmakaha commented on src/routes/authRoutes.js
> +    if (result.error) {
Unnecessary

2020-11-03 19:31 UTC, rafaelmakaha commented on src/routes/topicRoutes.js
> +    if (result.error) {
Unnecessary

2020-11-03 19:31 UTC, rafaelmakaha commented on src/routes/topicRoutes.js
> +    if (result.error) {
Unnecessary

2020-11-03 19:48 UTC, guilhermedelyra commented on .eslintrc.json
> +    ],
por que o prettier foi removido?

2020-11-03 23:37 UTC, guilhermedelyra requested changes

2020-11-03 23:37 UTC, guilhermedelyra commented on package.json
> +    "eslint-plugin-prettier": "^3.1.4",
isso é uma dev dependencie.

2020-11-09 21:12 UTC, joaovitorml approved these changes
gostei e aprovei

2020-11-14 16:24 UTC, merged