I119 modificar funcionamento do like
fga-eps-mds/2020.1-Grupo2-BackEnd pull request #123
Opened 2020-11-11 03:15 UTC by Marofelipe

Essa issue tem como objetivo resolver problemas encontrados no frontend, como:

- Não há um controle de quantidade de likes,
- O like não é vinculado a um usuario,
- As respostas das requisições são apenas mensagens;

Visto isso, o fechamento dessa issue deve ser feito se e somente se os itens a seguir forem compridos.
- [ ] Criar uma model para os Likes:
1. - [ ] Cada like deve referenciar o tópico || comentário que ele pertence;
2. - [ ] Cada like deve referenciar o usuário que deu o like;  
3. - [ ] Cada like calcular e armazenar a subtração dos likes/deslikes; 
- [ ] Alterar o funcionamento do router dos likes:
1. - [ ] As respostas de cada rota deve ser alterada para devolver o tópico || comentáro ja atualizado;
2. - [ ] As rotas devem receber o ID do usuario via token || url;
3. - [ ] As rotas devem verificar se o ID do usuario ja se encontra dentro do array de usuários;
- [ ] Aplicar a autentificação no router:
1. - [ ] Deve ser verificado se o usuario está logado via token;
2. - [ ] O ID do usuario deve ser passado e recuperado via token;

2020-11-11 03:23 UTC, Marofelipe commented
Quantidade  de likes não é contabilizada, vou implementar apos o deslike funcionar

2020-11-11 22:22 UTC, rafaelmakaha requested changes
Alterar pontos informados

2020-11-11 22:22 UTC, rafaelmakaha commented on src/routes/commentRoutes.js
> +    const topic = await Topic.findById(req.params.topicId).populate([
Remover este populate

2020-11-11 22:22 UTC, rafaelmakaha commented on src/routes/commentRoutes.js
> +    const topicCorrect = await Topic.findById(req.params.topicId).populate([
Este populate está correto

2020-11-11 22:22 UTC, rafaelmakaha commented on src/routes/topicRoutes.js
> +      { path: 'user' },
Não precisa do user criador do tópico

2020-11-11 22:22 UTC, rafaelmakaha commented on src/routes/topicRoutes.js
> +      { path: 'toppic' },
Remover toppic

2020-11-11 22:22 UTC, rafaelmakaha commented on src/routes/topicRoutes.js
> +        { path: 'user' },
Remover User e toppic

2020-11-11 22:22 UTC, rafaelmakaha commented on src/index.js
>  // mongodb://mongo:27017/backend => banco de dados da develop
Remover comentários

2020-12-02 20:16 UTC, rafaelmakaha approved these changes
New like and dislike system is working fine.

2020-12-02 20:16 UTC, merged