Topic Issues
fga-eps-mds/2020.1-Grupo2-BackEnd pull request #82
Opened 2020-09-24 15:51 UTC by senaarth

This pull request is willing to solve the issues about the user stories from sprint 3 that were about: 

- [ ] Create Topic
- [ ] Edit Topic
- [ ] Delete Topic
- [ ] Upvote and Downvote in topic

- [ ] Create comment in a topic
- [ ] Edit comment made
- [ ] Delete comment made
- [ ] Upvote and Downvote in comment

2020-10-11 19:38 UTC, senaarth commented
Features already finished and branch with no conflicts with develop, please review this PR.

2020-10-15 15:58 UTC, guilhermedelyra requested changes

2020-10-15 15:58 UTC, guilhermedelyra commented on src/routes/itemRoutes.js
> +const Item = require('../models/Item');
o problema é que na models o arquivo 'item' está salvo em minusculo (e nao com o I maiusculo), então dá erro de import

falando nisso, nao seria interessante remover logo todos os scripts referenciando 'Item'?

2020-10-15 16:00 UTC, senaarth commented on src/routes/itemRoutes.js
> +const Item = require('../models/Item');
Deixei estes arquivos por motivo de nao terem sido feitos por mim, mas pra falar a verdade tambem acho que seria interessante remover logo

2020-10-15 16:51 UTC, guilhermedelyra approved these changes
tudo ok!

2020-10-15 16:52 UTC, merged